version: "3.7"

services:
  plataforma_ibp_api:
    image: jbtech/plataforma-ibp-api:latest
    volumes:
      - /root/base_dados/plataforma_ibp_api/.env:/app/.env:ro
    networks:
      - jbtechinnova
    deploy:
      replicas: 1

  nginx_plataforma_ibp_api:
    image: nginx:1.25-alpine
    volumes:
      - /root/base_dados/plataforma_ibp_api/deploy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - jbtechinnova
    depends_on:
      - plataforma_ibp_api
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=jbtechinnova"
        - "traefik.http.routers.plataforma-ibp-api.rule=Host(`ibp-api-qa.jbtechinnova.com`)"
        - "traefik.http.routers.plataforma-ibp-api.entrypoints=websecure"
        - "traefik.http.routers.plataforma-ibp-api.tls=true"
        - "traefik.http.routers.plataforma-ibp-api.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.plataforma-ibp-api.loadbalancer.server.port=80"
        - "traefik.http.routers.plataforma-ibp-api-http.rule=Host(`ibp-api-qa.jbtechinnova.com`)"
        - "traefik.http.routers.plataforma-ibp-api-http.entrypoints=web"
        - "traefik.http.middlewares.plataforma-ibp-api-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.plataforma-ibp-api-http.middlewares=plataforma-ibp-api-redirect"
        - "traefik.http.routers.plataforma-ibp-api-http.service=plataforma-ibp-api"

networks:
  jbtechinnova:
    external: true
    name: jbtechinnova
